### ISSUE TITLE
MissingPluginException(No implementation found for method convert on channel flutter_open_chinese_convert)

### ISSUE THREAD

**Issue by rocccp** [zonble/flutter_open_chinese_convert#8]
```
var text1 = '鼠标里面的硅二极管坏了，导致光标分辨率降低。';
var option = ChineseConverter.allOptions[0];
 var result = await ChineseConverter.convert(text1,option,inBackground: true );
```

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method convert on channel flutter_open_chinese_convert)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      ChineseConverter.convert (package:flutter_open_chinese_convert/src/chinese_converter.dart:42:9)
<asynchronous suspension>
#2      _ChineseConvertWidgetState.build.<anonymous closure> (package:personal/screens/chinese/chinese_convert_widget.dart:28:32)
<asynchronous suspension>

**Comment by winsonet** [comment]
same error :(

**Comment by zonble** [comment]
Which platform are you running on?

**Comment by zonble** [comment]
This should be fixed on the main branch
